# Generated by Django 2.0.3 on 2018-03-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiziapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(default='', max_length=100, verbose_name='视频'),
        ),
    ]
