# Generated by Django 2.0.3 on 2018-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiziapp', '0003_auto_20180329_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='infomation',
            field=models.CharField(default='', max_length=100, verbose_name='详细信息'),
        ),
    ]
