# Generated by Django 2.0.3 on 2018-03-30 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiziapp', '0004_userinfo_infomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercourse',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='报名学生'),
        ),
    ]
